# 端口
server:
  port: 8082

# sa-token配置
sa-token:
  # token名称 (同时也是cookie名称)
  token-name: satoken-server
  # OAuth2.0 配置
  oauth2:
    is-code: true
    is-implicit: true
    is-password: nacos true
    is-client: true

spring:
  profiles:
    active: weiran
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2B8&useSSL=false&allowPublicKeyRetrieval=true&autoReconnect=true&failOverReadOnly=false
    username: root
    password: 123456
  # redis Sa-token的框架集成，只需要引入maven依赖就可以了
  redis:
    # Redis数据库索引（默认为0）
    database: 0
    # Redis服务器地址
    host: 127.0.0.1
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password: 123456
    # 连接超时时间（毫秒）
    timeout: 5000
    lettuce:
      pool:
        # 连接池最大连接数
        max-active: 200
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
        # 连接池中的最大空闲连接
        max-idle: 10
        # 连接池中的最小空闲连接
        min-idle: 0

#tx-lcn相关配置
tx-lcn:
  springcloud:
    loadbalance:
      enabled: true
  client:
    ## tx-manager 的配置地址，可以指定TM集群中的任何一个或多个地址
    ## tx-manager 下集群策略，每个TC都会从始至终<断线重连>与TM集群保持集群大小个连接。
    ## TM方，每有TM进入集群，会找到所有TC并通知其与新TM建立连接。
    ## TC方，启动时按配置与集群建立连接，成功后，会再与集群协商，查询集群大小并保持与所有TM的连接
    manager-address: 127.0.0.1:8207
  #是否开启日志记录。当开启以后需要配置对应logger的数据库连接配置信息。
  logger:
    enabled: false

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:mapper/*Mapper.xml
  type-aliases-package: com.weiran.studentmanager.mapper
  global-config:
    # 逻辑删除配置
    db-config:
      # 删除前
      logic-not-delete-value: 0
      # 删除后
      logic-delete-value: 1

#日志配置文件
logging:
  config: classpath:logback.xml

  swagger:
    production: false
    basic:
      enable: true
      username: weiran
      password: nacos


