server:
  port: 7000

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    # 全局消息确认消费默认
    listener.simple.acknowledge-mode: auto

rocketmq:
  name-server: 127.0.0.1:9876
  producer:
    group: seckill-producer-rocketmq-group
