spring:
  main:
    # 一个启动时候的覆盖bug
    allow-bean-definition-overriding: true
  profiles:
    active: weiran
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 1000MB
      location:  /data/upload_tmp