spring:
  main:
    # Bean同名注册出现的bug，true则是覆盖同名注册的Bean
    allow-bean-definition-overriding: true
  profiles:
    active: weiran
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 1000MB
      location:  /data/upload_tmp